CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(50),
    DNUMBER INT PRIMARY KEY,
    MGRSSN INT,
    MGRSTARTDATE DATE
);

CREATE TABLE EMPLOYEE (
    FNAME VARCHAR(50),
    MINIT VARCHAR(1),
    LNAME VARCHAR(50),
    SSN INT PRIMARY KEY,
    BDATE DATE,
    ADDRESS VARCHAR(50),
    SEX VARCHAR(1),
    SALARY INT,
    SUPERSSN INT,
    DNO INT,

    FOREIGN KEY (SUPERSSN)
        REFERENCES EMPLOYEE(SSN),

    FOREIGN KEY (DNO)
        REFERENCES DEPARTMENT(DNUMBER)
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_MANAGER
FOREIGN KEY (MGRSSN)
REFERENCES EMPLOYEE(SSN);

CREATE TABLE DEPT_LOCATION (
    DNUMBER INT,
    DLOCATION VARCHAR(50),

    PRIMARY KEY (DNUMBER, DLOCATION),

    FOREIGN KEY (DNUMBER)
        REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE PROJECT (
    PNAME VARCHAR(50),
    PNUMBER INT PRIMARY KEY,
    PLOCATION VARCHAR(50),
    DNUM INT,

    FOREIGN KEY (DNUM)
        REFERENCES DEPARTMENT(DNUMBER)
);

CREATE TABLE WORKS_ON (
    ESSN INT,
    PNO INT,

    PRIMARY KEY (ESSN, PNO),

    FOREIGN KEY (ESSN)
        REFERENCES EMPLOYEE(SSN),

    FOREIGN KEY (PNO)
        REFERENCES PROJECT(PNUMBER)
);

CREATE TABLE DEPENDENT (
    ESSN INT,
    DEPENDENT_NAME VARCHAR(50),
    SEX VARCHAR(1),
    BDATE DATE,
    RELATIONSHIP VARCHAR(50),

    PRIMARY KEY (ESSN, DEPENDENT_NAME),

    FOREIGN KEY (ESSN)
        REFERENCES EMPLOYEE(SSN)
);

INSERT INTO EMPLOYEE
VALUES ('MUHAMMAD', 'S', 'SAKR', 1, '2006-10-01', 'ZAGAZIG', 'M', 40000, 1234, 1);

INSERT INTO EMPLOYEE
VALUES ('SHROUQ', 'M', 'AHMED', 2, '2006-05-24', 'ZAGAZIG', 'F', 20000, 1234, 1);

INSERT INTO EMPLOYEE
VALUES ('SHROUQ', 'M', 'AHMED', 4, '2006-05-24', 'ZAGAZIG', 'F', 20000, 1234, 1);

INSERT INTO EMPLOYEE
VALUES ('SHROUQ', 'M', 'AHMED', 10, '2006-05-24', 'ZAGAZIG', 'F', 20000, 1234, 10);

INSERT INTO DEPARTMENT
VALUES ('COMPUTER SCIENCE', 2, 1234, '2026-10-01');

INSERT INTO DEPARTMENT
VALUES ('COMPUTER SCIENCE', 3, 968574, '2026-10-01');

INSERT INTO DEPARTMENT
VALUES ('COMPUTER SCIENCE', 10, 10, '2026-10-01');

INSERT INTO PROJECT
VALUES ('COMPUTER SCINECE', 1, 'FCI-ZU', 2);

-----------------------------------

SELECT *
FROM EMPLOYEE;

-----------------------------------

SELECT FNAME, LNAME, SALARY, DNO
FROM EMPLOYEE;


-----------------------------------

SELECT PNAME, PLOCATION, DNUM
FROM PROJECT;


-----------------------------------

SELECT
    FNAME || ' ' || LNAME AS FULLNAME,
    SALARY * 12 * 0.10 AS "ANNUAL COMM"
FROM EMPLOYEE;


-----------------------------------

SELECT SSN, FNAME, LNAME
FROM EMPLOYEE
WHERE SALARY > 1000;


-----------------------------------

SELECT SSN, FNAME, LNAME
FROM EMPLOYEE
WHERE SEX = 'F';


-----------------------------------

SELECT DNUMBER, FNAME, SSN
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
    ON D.MGRSSN = E.SSN
WHERE E.SSN = 968574;


-----------------------------------

SELECT P.PNUMBER, P.PNAME, P.PLOCATION
FROM PROJECT P
INNER JOIN DEPARTMENT D
    ON D.DNUMBER = P.DNUM
WHERE D.DNUMBER = 10;
